### ISSUE TITLE
CircleCI Pipeline in status checks

### ISSUE THREAD

**Issue by andyw8** [andyw8/pocket-ruby#108]
Hi @turadg @jasonngpt @ryanmuller

I'm noticing that the old and unused Circle CI pipeline is showing as a failure in the PR status checks, e.g. https://github.com/turadg/pocket-ruby/pull/107/commits

I expect it needs to be disabled in the branch settings for `master` but I don't have the necessary permissions. Is someone able to do that?

It's not a required check so it doesn't prevent PRs being merged, but it would be nice if we can remove it.

Thanks

**Comment by turadg** [comment]
It sounds like you don't have a use for Circle CI. I've updated the Circle CI project settings to not push status updates to GitHub. I've also want to disabled the webhook that notifies it to do anything: https://github.com/turadg/pocket-ruby/settings/hooks (@andyw8 you can re-activated or delete at will)

**Comment by andyw8** [comment]
Thanks @turadg. I can't access that config page, but it seems to be working correctly now, no CircleCI status showing: https://github.com/turadg/pocket-ruby/pull/109

**Comment by turadg** [comment]
Ah, I didn't realize "Collaborator" doesn't grant access. I tried to make you admin but Collaborator is the only option for a [personal account repository](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository).

You're doing all the work at this point. If you want me to transfer the repo to you or your organization, I'm happy to.

**Comment by andyw8** [comment]
Thanks @turadg, I'm not planning any big changes, but happy to take over if you want to transfer to my personal account (`andyw8`).

**Comment by turadg** [comment]
@andyw8 I tried but it collides with https://github.com/andyw8/pocket-ruby. If you delete that I'll transfer it over.

**Comment by andyw8** [comment]
Ahh, deleted, can you try again?

**Comment by andyw8** [comment]
Thanks, the transfer was successful.

@jasonngpt and @ryanmuller – do you want to stay on as maintainers? If I don't hear anything back by the end of the year then I'll assume not, and can remove you.

**Comment by andyw8** [comment]
(done)
