### ISSUE TITLE
Faraday Timeout settings?

### ISSUE THREAD

**Issue by adamklaff** [andyw8/pocket-ruby#19]
I have a worker set to retrieve my Pocket contents and sometimes it takes several seconds to get a response. Using the gem, what is the best way to tweak the Faraday timeout settings to allow for this delay?

**Comment by jasonngpt** [comment]
Hello @adamklaff, there is no timeout setting for Faraday in the gem currently. From the looks of it, we can set a reasonable default timeout value in configuration.rb, so this timeout will be taken into effect when creating the Faraday connection in connection.rb

If there is a big need for user-defined timeout settings, a possibility is to use environment variables.

Thoughts? Want to try adding the default timeout first?

**Comment by adamklaff** [comment]
Yes that could work well and might be preferable to changing global Faraday settings. Thanks! Any idea where I would specify that in connection.rb?

**Comment by jasonngpt** [comment]
Referring to the 1st answer [here](http://stackoverflow.com/questions/8098584/faraday-timeout), I think you can specify the timeout in the options. Try it out and see if it works? Create a PR if it is okay. :)

**Comment by andyw8** [comment]
I haven't observed any timeouts while using the API, even when retrieving the maximum amount of records. As this issue is almost 6 years old, I think it may no longer be valid, so I'm going to close this. Please re-open it, or create a new issue, if this problem re-occurs.
