### ISSUE TITLE
Actualize faraday dependencies?

### ISSUE THREAD

**Issue by ShockwaveNN** [andyw8/pocket-ruby#23]
Currently gem locked on
```
'faraday', ['>= 0.7']`
'faraday_middleware', '~> 0.9'
```

Both of those gems reach version 1.0

**Comment by andyw8** [comment]
I have a fork here with that constraint removed:

https://github.com/andyw8/pocket-ruby

**Comment by ShockwaveNN** [comment]
@andyw8 Maybe if author can confirm that he's stopped development of this version he could promote your to some kind of admins, so we do not need to use fork

@turadg Could you confirm that you're not planning update this project?

**Comment by turadg** [comment]
Correct! Thanks for the ping @ShockwaveNN .

Happy to extend adminship to a responsible maintainer.

**Comment by andyw8** [comment]
I'm happy to take over if @turadg agrees.

You can DM me on Twitter to co-ordinate: https://twitter.com/andyw8

**Comment by turadg** [comment]
Invited you as a collaborator @andyw8 . @jasonngpt  and @ryanmuller also have access.

**Comment by andyw8** [comment]
Thanks @turadg. Do you want to add me as an owner so I can push new versions to rubygems, or handle that yourself?

**Comment by turadg** [comment]
Happy to add you to [the Gemspec](https://github.com/turadg/pocket-ruby/blob/master/pocket-ruby.gemspec#L13) but I don't know which email to use, so please go ahead and edit.

**Comment by andyw8** [comment]
I think it needs to be changed on rubygems.org rather than the gemspec, you should be able to add `andyw8` here:

https://rubygems.org/gems/turadg-pocket-ruby/owners

**Comment by andyw8** [comment]
All seems good, I just released v0.0.7 with this fix.

https://rubygems.org/gems/pocket-ruby

**Comment by ShockwaveNN** [comment]
Thanks you're all
Can confirm that original issues is fixed and actual faraday is used with v0.0.7
